const $=id=>document.getElementById(id);
let ws=null,myId=null,roomCode=null,cfg=null,state=null;
const keys={}; const canvas=$('canvas'),ctx=canvas.getContext('2d');
const WORLD={w:1600,h:900};
function wsUrl(){return `${location.protocol==='https:'?'wss':'ws'}://${location.host}`}
function setConnection(ok){$('connection').textContent=ok?'ONLINE':'OFFLINE';$('connection').className=ok?'':'off'}
function connect(cb){if(ws&&ws.readyState<=1)return;ws=new WebSocket(wsUrl());ws.onopen=()=>{setConnection(true);cb?.()};ws.onclose=()=>setConnection(false);ws.onerror=()=>setConnection(false);ws.onmessage=e=>handle(JSON.parse(e.data))}
function send(m){if(ws?.readyState===1)ws.send(JSON.stringify(m))}
function nameVal(){return (($('name').value||'Player').trim().slice(0,16)||'Player')}
$('create').onclick=()=>connect(()=>send({type:'create',name:nameVal()}));
$('join').onclick=()=>{const code=$('room').value.trim().toUpperCase();if(code.length!==6)return alert('방 코드는 6자리입니다.');connect(()=>send({type:'join',room:code,name:nameVal()}))};
$('quick').onclick=async()=>{await loadRooms(true)};
$('start').onclick=()=>send({type:'start'});$('leave').onclick=()=>location.reload();
function handle(m){if(m.type==='joined'){myId=m.id;roomCode=m.room;cfg=m.config;$('home').hidden=true;$('waiting').hidden=false;$('room-code').textContent=roomCode;$('room-title').textContent=roomCode;loadRooms()}if(m.type==='error')alert(m.message);if(m.type==='system'){showMessage(m.message)}if(m.type==='state'){state=m;renderLobby();if(m.running){$('waiting').hidden=true;$('game').hidden=false;requestAnimationFrame(render)}}}
function renderLobby(){if(!state)return;$('players').innerHTML=state.players.map((p,i)=>`<div class="player-row"><span>${i+1}. ${escapeHtml(p.name)}</span><span class="role">${p.role==='oni'?'AO ONI':''}</span></div>`).join('')}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function showMessage(t){$('message').textContent=t;const d=document.createElement('div');d.className='msg';d.textContent=t;$('chatbox').appendChild(d);setTimeout(()=>d.remove(),3000)}
async function loadRooms(autoJoin=false){try{const res=await fetch('/api/rooms',{cache:'no-store'});const rooms=await res.json();const open=rooms.filter(r=>!r.running&&r.players<r.maxPlayers);if(autoJoin&&open[0]){$('room').value=open[0].code;$('join').click();return}$('room-list').innerHTML=open.length?open.map(r=>`<div class="room-item"><span>ROOM <b>${r.code}</b></span><span class="count">${r.players}/${r.maxPlayers}</span><button data-code="${r.code}">참가</button></div>`).join(''):'<div class="empty">현재 열린 방이 없습니다.</div>';$('room-list').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('room').value=b.dataset.code;$('join').click()})}catch{$('room-list').innerHTML='<div class="empty">서버에 연결할 수 없습니다.</div>'}}
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys[k]=true;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault()});window.addEventListener('keyup',e=>delete keys[e.key.toLowerCase()]);window.addEventListener('blur',()=>Object.keys(keys).forEach(k=>delete keys[k]));
setInterval(()=>{if(!state?.running)return;let dir={x:0,y:-1};if(keys.arrowdown)dir={x:0,y:1};else if(keys.arrowleft)dir={x:-1,y:0};else if(keys.arrowright)dir={x:1,y:0};send({type:'input',keys:{w:!!keys.w,a:!!keys.a,s:!!keys.s,d:!!keys.d},shoot:!!(keys.arrowup||keys.arrowdown||keys.arrowleft||keys.arrowright),dir,reload:!!keys.r,skill:!!keys.k})},50);
function worldToView(x,y,me){const scale=Math.min(canvas.width/WORLD.w,canvas.height/WORLD.h);const vw=canvas.width/scale,vh=canvas.height/scale;let camX=me?me.x-vw/2:WORLD.w/2-vw/2,camY=me?me.y-vh/2:WORLD.h/2-vh/2;camX=Math.max(0,Math.min(WORLD.w-vw,camX));camY=Math.max(0,Math.min(WORLD.h-vh,camY));return {x:(x-camX)*scale,y:(y-camY)*scale,scale,camX,camY}}
function drawCorridor(){ctx.fillStyle='#000';ctx.fillRect(0,0,canvas.width,canvas.height);const s=Math.min(canvas.width/WORLD.w,canvas.height/WORLD.h);for(let i=0;i<17;i++){const x=150+i*88;ctx.fillStyle=i%2?'#6e6a61':'#858178';ctx.fillRect((x-12-worldCam.camX)*s,(130-worldCam.camY)*s,24,640*s)}for(let y=170;y<800;y+=58){ctx.fillStyle=(y/58)%2?'#5f5b55':'#77726a';ctx.fillRect((170-worldCam.camX)*s,(y-worldCam.camY)*s,1260*s,28*s)}ctx.fillStyle='#2f2b27';ctx.fillRect((170-worldCam.camX)*s,(150-worldCam.camY)*s,1260*s,18*s);ctx.fillRect((170-worldCam.camX)*s,(790-worldCam.camY)*s,1260*s,18*s);ctx.fillStyle='#241f1c';ctx.fillRect((410-worldCam.camX)*s,(168-worldCam.camY)*s,360*s,622*s);ctx.fillStyle='#000';ctx.fillRect((450-worldCam.camX)*s,(210-worldCam.camY)*s,280*s,540*s)}
let worldCam={camX:0,camY:0};
function drawSprite(p,me=false){const t=worldToView(p.x,p.y,state.players.find(x=>x.id===myId));worldCam=t;const x=t.x,y=t.y,s=Math.max(1,t.scale);ctx.save();ctx.translate(Math.round(x),Math.round(y));ctx.imageSmoothingEnabled=false;const oni=p.role==='oni';ctx.fillStyle=oni?'#b52222':'#c83c2f';ctx.fillRect(-9*s,-12*s,18*s,18*s);ctx.fillStyle=oni?'#7f1414':'#f06b2d';ctx.fillRect(-6*s,-18*s,12*s,7*s);ctx.fillStyle='#111';ctx.fillRect(-5*s,-3*s,3*s,3*s);ctx.fillRect(2*s,-3*s,3*s,3*s);ctx.fillStyle='#2f2b2b';ctx.fillRect(-7*s,6*s,5*s,7*s);ctx.fillRect(2*s,6*s,5*s,7*s);if(me){ctx.strokeStyle='#fff';ctx.lineWidth=1*s;ctx.strokeRect(-12*s,-21*s,24*s,38*s)}ctx.font=`${10*s}px Courier New`;ctx.textAlign='center';ctx.fillStyle='#fff';ctx.fillText(p.name,0,-25*s);ctx.restore()}
function render(){if(!state?.running)return;const me=state.players.find(p=>p.id===myId);const t=worldToView(me?.x||800,me?.y||450,me);worldCam=t;drawCorridor();for(const i of state.items){const q=worldToView(i.x,i.y,me);ctx.fillStyle=i.type==='goldMarble'?'#e0c245':'#4ea5ff';ctx.fillRect(q.x-4,q.y-4,8,8)}for(const b of state.bullets){const q=worldToView(b.x,b.y,me);ctx.fillStyle='#f8edba';ctx.fillRect(q.x-2,q.y-2,4,4)}state.players.forEach(p=>{if(p.alive)drawSprite(p,p.id===myId)});$('role').textContent=(me?.role||'human').toUpperCase();$('timer').textContent=format(state.roundTimer);$('ammo').textContent=`AMMO ${me?.ammo??0}`;$('skill').textContent='SKILL READY';requestAnimationFrame(render)}
function format(s){return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
loadRooms();setInterval(loadRooms,3000);
